CREATE DATABASE PSMS;
USE psms;

CREATE TABLE Province (
    Province_ID varchar(10) PRIMARY KEY,
    Province_Name VARCHAR(50) NOT NULL,
    Province_Code VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE District (
    District_ID varchar(20) PRIMARY KEY,
    District_Name VARCHAR(50) NOT NULL,
    Province_ID varchar(10),
    
    CONSTRAINT FK_DISTRICT_PROVINCE
    FOREIGN KEY (Province_ID)
    REFERENCES Province(Province_ID)
    ON UPDATE CASCADE
	ON DELETE RESTRICT
);
create table coach (
	COACH_ID VARCHAR (20) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
   
	COACH_NAME VARCHAR(101)
		GENERATED ALWAYS AS (CONCAT(FIRST_NAME, ' ', LAST_NAME)) STORED,
	
    QUALIFICATION VARCHAR(100) NOT NULL,
    LICENCE_NO VARCHAR(20) UNIQUE,
    GENDER VARCHAR(10),
    DISTRICT_ID VARCHAR(20),
    
    PRIMARY KEY (COACH_ID),
    CONSTRAINT FK_COACH_DISTRICT
    FOREIGN KEY (DISTRICT_ID)
    REFERENCES DISTRICT(DISTRICT_ID)
);

CREATE TABLE ATHLETE (
    ATHLETE_ID VARCHAR(20) NOT NULL ,
    DISTRICT_ID VARCHAR(10) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    
    FULL_NAME VARCHAR(101)
		GENERATED ALWAYS AS (CONCAT(FIRST_NAME, ' ', LAST_NAME)) STORED,
    
    NATIONAL_ID VARCHAR(20) UNIQUE,
    REG_NO VARCHAR(20) UNIQUE,
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10),
    CONTACT_NO VARCHAR(15),
    COACH_ID VARCHAR(20),
    
    PRIMARY KEY (ATHLETE_ID),
    
    CONSTRAINT FK_ATHLETE_DISTRICT
    FOREIGN KEY (DISTRICT_ID)
    REFERENCES District(District_ID)
    ON UPDATE CASCADE
	ON DELETE RESTRICT,
    
    CONSTRAINT FK_ATHLETE_COACH
    FOREIGN KEY (COACH_ID)
    REFERENCES COACH(COACH_ID)
    ON UPDATE CASCADE
	ON DELETE SET NULL
);

CREATE TABLE SPORT(
	SPORT_NAME VARCHAR (50) NOT NULL,
    SPORT_ID VARCHAR (20),
    
    primary key (SPORT_ID)
);

CREATE TABLE VENUE(
	VENUE_ID VARCHAR(20),
    VENUE_NAME VARCHAR(100) NOT NULL,
    CAPACITY INT,
    
    STREET VARCHAR(100) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	POSTAL_CODE VARCHAR(10) NOT NULL,

	FULL_ADDRESS VARCHAR(170)
		GENERATED ALWAYS AS (
		CONCAT(STREET, ', ', CITY, ' ', POSTAL_CODE)
		) STORED,
	
    PRIMARY KEY (VENUE_ID)
);

CREATE TABLE MEDAL(
	MEDAL_ID VARCHAR(20),
    DESCRIPTION VARCHAR(50),
    MEDAL_TYPE VARCHAR (15) NOT NULL,
    
    PRIMARY KEY (MEDAL_ID)
);

CREATE TABLE EVENT(
	SPORT_ID VARCHAR(20),
    VENUE_ID VARCHAR(20),
    EVENT_ID VARCHAR(20),
    EVENT_CODE VARCHAR(20),
    EVENT_NAME VARCHAR(100),
    EVENT_CATEGORY ENUM('Individual','Team','Relay'),
    
    PRIMARY KEY(EVENT_ID),
    
    CONSTRAINT FK_EVENT_SPORT
    FOREIGN KEY (SPORT_ID)
    REFERENCES SPORT(SPORT_ID)
    ON DELETE RESTRICT
	ON UPDATE CASCADE,

    CONSTRAINT FK_EVENT_VENUE
    FOREIGN KEY (VENUE_ID)
    REFERENCES VENUE(VENUE_ID)
    ON DELETE RESTRICT
	ON UPDATE CASCADE
);

CREATE TABLE SPORT_MATCH (
	MATCH_ID VARCHAR(20),
    MATCH_DATE DATE,
    ROUND INT DEFAULT 1,
    EVENT_ID VARCHAR(20),
    VENUE_ID VARCHAR(20),
    
    PRIMARY KEY (MATCH_ID),
    CONSTRAINT FK_MATCH_EVENT
	FOREIGN KEY (EVENT_ID)
	REFERENCES EVENT(EVENT_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

	CONSTRAINT FK_MATCH_VENUE
	FOREIGN KEY (VENUE_ID)
	REFERENCES VENUE(VENUE_ID)
	ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE PARTICIPATION(
	PARTICIPANT_ID VARCHAR(20),
    EVENT_ID VARCHAR(20),
    ATHLETE_ID VARCHAR(20),
    RESULT VARCHAR(15),
    POSITION VARCHAR(10),
    REMARKS VARCHAR(50),
    MEDAL_ID VARCHAR(20),
    
    PRIMARY KEY(ATHLETE_ID,EVENT_ID,PARTICIPANT_ID),
    
    CONSTRAINT FK_PARTICIPATION_ATHLETE
    FOREIGN KEY (ATHLETE_ID)
    REFERENCES ATHLETE(ATHLETE_ID),

    CONSTRAINT FK_PARTICIPATION_EVENT
    FOREIGN KEY (EVENT_ID)
    REFERENCES EVENT(EVENT_ID)
    ON DELETE CASCADE,
    
    CONSTRAINT FK_PARTICIPATION_MEDAL
	FOREIGN KEY (MEDAL_ID)
	REFERENCES MEDAL(MEDAL_ID)
);

CREATE TABLE INJURY_RECORD (
	INJURY_ID VARCHAR(20),
    ATHLETE_ID VARCHAR(20),
    INJURY_DESCRIPTION VARCHAR(50),
	INJURY_DATE DATE,
    RECOVERY_DATE DATE,
    REMARKS VARCHAR(50),
    
    PRIMARY KEY (ATHLETE_ID,INJURY_ID),
    
    CONSTRAINT FK_INJURY_ATHLETE
    FOREIGN KEY (ATHLETE_ID)
    REFERENCES ATHLETE(ATHLETE_ID)
    ON DELETE CASCADE
);

CREATE TABLE DISTRICT_COMPETES (
    District_Compete_ID VARCHAR(10) PRIMARY KEY,
    District_ID_1 VARCHAR(20),
    District_ID_2 VARCHAR(20),
    Event_ID VARCHAR(20),
    Match_Date DATE,
    Venue VARCHAR(50),
    Winner_District_ID VARCHAR(20),
    Result VARCHAR(50),
    Remarks VARCHAR(100),

    CONSTRAINT FK_DC_DISTRICT1
        FOREIGN KEY (District_ID_1)
        REFERENCES DISTRICT(District_ID),

    CONSTRAINT FK_DC_DISTRICT2
        FOREIGN KEY (District_ID_2)
        REFERENCES DISTRICT(District_ID),

    CONSTRAINT FK_DC_EVENT
        FOREIGN KEY (Event_ID)
        REFERENCES EVENT(Event_ID),

    CONSTRAINT FK_DC_WINNER
        FOREIGN KEY (Winner_District_ID)
        REFERENCES DISTRICT(District_ID)
);

INSERT INTO Province (Province_ID, Province_Name, Province_Code) VALUES
('P001', 'Western', 'WP'),
('P002', 'Central', 'CP'),
('P003', 'Southern', 'SP'),
('P004', 'Northern', 'NP'),
('P005', 'Eastern', 'EP'),
('P006', 'North Western', 'NWP'),
('P007', 'North Central', 'NCP'),
('P008', 'Uva', 'UP'),
('P009', 'Sabaragamuwa', 'SGP');

INSERT INTO District (District_ID, District_Name, Province_ID) VALUES
-- Western Province
('D001', 'Colombo', 'P001'),
('D002', 'Gampaha', 'P001'),
('D003', 'Kalutara', 'P001'),
-- Central Province
('D004', 'Kandy', 'P002'),
('D005', 'Matale', 'P002'),
('D006', 'Nuwara Eliya', 'P002'),
-- Southern Province
('D007', 'Galle', 'P003'),
('D008', 'Matara', 'P003'),
('D009', 'Hambantota', 'P003'),
-- Northern Province
('D010', 'Jaffna', 'P004'),
('D011', 'Kilinochchi', 'P004'),
('D012', 'Mannar', 'P004'),
('D013', 'Mullaitivu', 'P004'),
('D014', 'Vavuniya', 'P004'),
-- Eastern Province
('D015', 'Batticaloa', 'P005'),
('D016', 'Ampara', 'P005'),
('D017', 'Trincomalee', 'P005'),
-- North Western Province
('D018', 'Kurunegala', 'P006'),
('D019', 'Puttalam', 'P006'),
-- North Central Province
('D020', 'Anuradhapura', 'P007'),
('D021', 'Polonnaruwa', 'P007'),
-- Uva Province
('D022', 'Badulla', 'P008'),
('D023', 'Monaragala', 'P008'),
-- Sabaragamuwa Province
('D024', 'Ratnapura', 'P009'),
('D025', 'Kegalle', 'P009');
























