CREATE TABLE Province (
    Province_ID INT PRIMARY KEY,
    Province_Name VARCHAR(50),
    Province_Code VARCHAR(10)
);

CREATE TABLE District (
    District_ID INT PRIMARY KEY,
    District_Name VARCHAR(50),
    Province_ID INT,
    FOREIGN KEY (Province_ID)
    REFERENCES Province(Province_ID)
);

CREATE TABLE ATHLETE (
    ATHLETE_ID VARCHAR(20) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    
    FULL_NAME VARCHAR(101) GENERATED ALWAYS AS (CONCAT(FIRST_NAME, ' ', LAST_NAME)) STORED,
    
    NATIONAL_ID VARCHAR(20),
    REG_NO VARCHAR(20),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10),
    CONTACT_NO VARCHAR(15),
    PRIMARY KEY (ATHLETE_ID)
);