CREATE DATABASE PSMS;
USE psms;

CREATE TABLE Province (
    Province_ID varchar(10) PRIMARY KEY,
    Province_Name VARCHAR(50) NOT NULL,
    Province_Code VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE District (
    District_ID varchar(20) PRIMARY KEY,
    District_Name VARCHAR(50) NOT NULL,
    Province_ID varchar(10),
    
    CONSTRAINT FK_DISTRICT_PROVINCE
    FOREIGN KEY (Province_ID)
    REFERENCES Province(Province_ID)
    ON UPDATE CASCADE
	ON DELETE RESTRICT
);
create table coach (
	COACH_ID VARCHAR (20) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
   
	COACH_NAME VARCHAR(101)
		GENERATED ALWAYS AS (CONCAT(FIRST_NAME, ' ', LAST_NAME)) STORED,
	
    LICENCE_NO VARCHAR(20) UNIQUE,
    GENDER VARCHAR(10),
    DISTRICT_ID VARCHAR(20),
    
    PRIMARY KEY (COACH_ID),
    CONSTRAINT FK_COACH_DISTRICT
    FOREIGN KEY (DISTRICT_ID)
    REFERENCES DISTRICT(DISTRICT_ID)
);

CREATE TABLE COACH_QUALIFICATION (
    COACH_ID VARCHAR(20),
    QUALIFICATION VARCHAR(100),

    PRIMARY KEY (COACH_ID, QUALIFICATION),

    CONSTRAINT FK_COACH_QUALIFICATION
    FOREIGN KEY (COACH_ID)
    REFERENCES COACH(COACH_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE ATHLETE (
    ATHLETE_ID VARCHAR(20) NOT NULL ,
    DISTRICT_ID VARCHAR(10) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    
    FULL_NAME VARCHAR(101)
		GENERATED ALWAYS AS (CONCAT(FIRST_NAME, ' ', LAST_NAME)) STORED,
    
    NATIONAL_ID VARCHAR(20) UNIQUE,
    REG_NO VARCHAR(20) UNIQUE,
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10),
    COACH_ID VARCHAR(20),
    
    PRIMARY KEY (ATHLETE_ID),
    
    CONSTRAINT FK_ATHLETE_DISTRICT
    FOREIGN KEY (DISTRICT_ID)
    REFERENCES District(District_ID)
    ON UPDATE CASCADE
	ON DELETE RESTRICT,
    
    CONSTRAINT FK_ATHLETE_COACH
    FOREIGN KEY (COACH_ID)
    REFERENCES COACH(COACH_ID)
    ON UPDATE CASCADE
	ON DELETE SET NULL
);

CREATE TABLE ATHLETE_CONTACT (
    ATHLETE_ID VARCHAR(20),
    CONTACT_NO VARCHAR(15),

    PRIMARY KEY (ATHLETE_ID, CONTACT_NO),

    CONSTRAINT FK_ATHLETE_CONTACT
    FOREIGN KEY (ATHLETE_ID)
    REFERENCES ATHLETE(ATHLETE_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE SPORT(
	SPORT_NAME VARCHAR (50) NOT NULL,
    SPORT_ID VARCHAR (20),
    
    primary key (SPORT_ID)
);

CREATE TABLE VENUE(
	VENUE_ID VARCHAR(20),
    VENUE_NAME VARCHAR(100) NOT NULL,
    CAPACITY INT,
    
    STREET VARCHAR(100) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	POSTAL_CODE VARCHAR(10) NOT NULL,

	FULL_ADDRESS VARCHAR(170)
		GENERATED ALWAYS AS (
		CONCAT(STREET, ', ', CITY, ' ', POSTAL_CODE)
		) STORED,
	
    PRIMARY KEY (VENUE_ID)
);

CREATE TABLE MEDAL(
	MEDAL_ID VARCHAR(20),
    DESCRIPTION VARCHAR(50),
    MEDAL_TYPE VARCHAR (15) NOT NULL,
    
    PRIMARY KEY (MEDAL_ID)
);

CREATE TABLE EVENT(
	SPORT_ID VARCHAR(20),
    VENUE_ID VARCHAR(20),
    EVENT_ID VARCHAR(20),
    EVENT_CODE VARCHAR(20),
    EVENT_NAME VARCHAR(100),
    EVENT_CATEGORY ENUM('Individual','Team','Relay'),
    
    PRIMARY KEY(EVENT_ID),
    
    CONSTRAINT FK_EVENT_SPORT
    FOREIGN KEY (SPORT_ID)
    REFERENCES SPORT(SPORT_ID)
    ON DELETE RESTRICT
	ON UPDATE CASCADE,

    CONSTRAINT FK_EVENT_VENUE
    FOREIGN KEY (VENUE_ID)
    REFERENCES VENUE(VENUE_ID)
    ON DELETE RESTRICT
	ON UPDATE CASCADE
);

CREATE TABLE SPORT_MATCH (
	MATCH_ID VARCHAR(20),
    MATCH_DATE DATE,
    ROUND INT DEFAULT 1,
    EVENT_ID VARCHAR(20),
    VENUE_ID VARCHAR(20),
    
    PRIMARY KEY (MATCH_ID),
    CONSTRAINT FK_MATCH_EVENT
	FOREIGN KEY (EVENT_ID)
	REFERENCES EVENT(EVENT_ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

	CONSTRAINT FK_MATCH_VENUE
	FOREIGN KEY (VENUE_ID)
	REFERENCES VENUE(VENUE_ID)
	ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE TABLE PARTICIPATION(
	PARTICIPANT_ID VARCHAR(20),
    EVENT_ID VARCHAR(20),
    ATHLETE_ID VARCHAR(20),
    RESULT VARCHAR(15),
    POSITION VARCHAR(10),
    REMARKS VARCHAR(50),
    MEDAL_ID VARCHAR(20),
    
    PRIMARY KEY(ATHLETE_ID,EVENT_ID,PARTICIPANT_ID),
    
    CONSTRAINT FK_PARTICIPATION_ATHLETE
    FOREIGN KEY (ATHLETE_ID)
    REFERENCES ATHLETE(ATHLETE_ID),

    CONSTRAINT FK_PARTICIPATION_EVENT
    FOREIGN KEY (EVENT_ID)
    REFERENCES EVENT(EVENT_ID)
    ON DELETE CASCADE,
    
    CONSTRAINT FK_PARTICIPATION_MEDAL
	FOREIGN KEY (MEDAL_ID)
	REFERENCES MEDAL(MEDAL_ID)
);

CREATE TABLE INJURY_RECORD (
	INJURY_ID VARCHAR(20),
    ATHLETE_ID VARCHAR(20),
    INJURY_DESCRIPTION VARCHAR(50),
	INJURY_DATE DATE,
    RECOVERY_DATE DATE,
    REMARKS VARCHAR(50),
    
    PRIMARY KEY (ATHLETE_ID,INJURY_ID),
    
    CONSTRAINT FK_INJURY_ATHLETE
    FOREIGN KEY (ATHLETE_ID)
    REFERENCES ATHLETE(ATHLETE_ID)
    ON DELETE CASCADE
);

CREATE TABLE DISTRICT_COMPETES (
    District_Compete_ID VARCHAR(10) PRIMARY KEY,
    District_ID_1 VARCHAR(20),
    District_ID_2 VARCHAR(20),
    Event_ID VARCHAR(20),
    Match_Date DATE,
    Venue VARCHAR(50),
    Winner_District_ID VARCHAR(20),
    Result VARCHAR(50),
    Remarks VARCHAR(100),

    CONSTRAINT FK_DC_DISTRICT1
        FOREIGN KEY (District_ID_1)
        REFERENCES DISTRICT(District_ID),

    CONSTRAINT FK_DC_DISTRICT2
        FOREIGN KEY (District_ID_2)
        REFERENCES DISTRICT(District_ID),

    CONSTRAINT FK_DC_EVENT
        FOREIGN KEY (Event_ID)
        REFERENCES EVENT(Event_ID),

    CONSTRAINT FK_DC_WINNER
        FOREIGN KEY (Winner_District_ID)
        REFERENCES DISTRICT(District_ID)
);

INSERT INTO Province (Province_ID, Province_Name, Province_Code) VALUES
('P001', 'Western', 'WP'),
('P002', 'Central', 'CP'),
('P003', 'Southern', 'SP'),
('P004', 'Northern', 'NP'),
('P005', 'Eastern', 'EP'),
('P006', 'North Western', 'NWP'),
('P007', 'North Central', 'NCP'),
('P008', 'Uva', 'UP'),
('P009', 'Sabaragamuwa', 'SGP');

INSERT INTO District (District_ID, District_Name, Province_ID) VALUES
-- Western Province
('D001', 'Colombo', 'P001'),
('D002', 'Gampaha', 'P001'),
('D003', 'Kalutara', 'P001'),
-- Central Province
('D004', 'Kandy', 'P002'),
('D005', 'Matale', 'P002'),
('D006', 'Nuwara Eliya', 'P002'),
-- Southern Province
('D007', 'Galle', 'P003'),
('D008', 'Matara', 'P003'),
('D009', 'Hambantota', 'P003'),
-- Northern Province
('D010', 'Jaffna', 'P004'),
('D011', 'Kilinochchi', 'P004'),
('D012', 'Mannar', 'P004'),
('D013', 'Mullaitivu', 'P004'),
('D014', 'Vavuniya', 'P004'),
-- Eastern Province
('D015', 'Batticaloa', 'P005'),
('D016', 'Ampara', 'P005'),
('D017', 'Trincomalee', 'P005'),
-- North Western Province
('D018', 'Kurunegala', 'P006'),
('D019', 'Puttalam', 'P006'),
-- North Central Province
('D020', 'Anuradhapura', 'P007'),
('D021', 'Polonnaruwa', 'P007'),
-- Uva Province
('D022', 'Badulla', 'P008'),
('D023', 'Monaragala', 'P008'),
-- Sabaragamuwa Province
('D024', 'Ratnapura', 'P009'),
('D025', 'Kegalle', 'P009');

INSERT INTO COACH 
(COACH_ID, FIRST_NAME, LAST_NAME, LICENCE_NO, GENDER, DISTRICT_ID)
VALUES
('C001','Kamal','Perera','LIC001','Male','D001'),
('C002','Nimal','Fernando','LIC002','Male','D004'),
('C003','Sunil','Silva','LIC003','Male','D007'),
('C004','Ruwan','Jayasinghe','LIC004','Male','D018'),
('C005','Tharindu','Bandara','LIC005','Male','D022'),
('C006','Chathura','Wickrama','LIC006','Male','D024');

INSERT INTO COACH_QUALIFICATION
(COACH_ID, QUALIFICATION)
VALUES
('C001','Level 1 Athletics Coach'),
('C001','First Aid Certificate'),
('C002','Level 2 Cricket Coach'),
('C003','Swimming Instructor Certificate'),
('C004','Diploma in Sports Coaching'),
('C005','National Coaching Certificate');

INSERT INTO SPORT
(SPORT_ID, SPORT_NAME)
VALUES
('S001','100m Running'),
('S002','Long Jump'),
('S003','Swimming'),
('S004','Cricket'),
('S005','Football'),
('S006','Volleyball');

INSERT INTO VENUE
(VENUE_ID, VENUE_NAME, CAPACITY, STREET, CITY, POSTAL_CODE)
VALUES
('V001','Sugathadasa Stadium',25000,'Kotahena Road','Colombo','01300'),
('V002','Kandy Sports Complex',15000,'Peradeniya Road','Kandy','20000'),
('V003','Galle International Stadium',35000,'Colombo Road','Galle','80000'),
('V004','Kurunegala Stadium',10000,'Negombo Road','Kurunegala','60000'),
('V005','Badulla Sports Ground',8000,'Main Street','Badulla','90000'),
('V006','Ratnapura Stadium',9000,'New Town Road','Ratnapura','70000');

INSERT INTO MEDAL
(MEDAL_ID, DESCRIPTION, MEDAL_TYPE)
VALUES
('M001','Gold Medal','Gold'),
('M002','Silver Medal','Silver'),
('M003','Bronze Medal','Bronze'),
('M004','Gold Medal','Gold'),
('M005','Silver Medal','Silver'),
('M006','Bronze Medal','Bronze');

INSERT INTO ATHLETE
(ATHLETE_ID,DISTRICT_ID,FIRST_NAME,LAST_NAME,NATIONAL_ID,REG_NO,DATE_OF_BIRTH,GENDER,COACH_ID)
VALUES
('A001','D001','Kasun','Perera','N001','R001','2004-05-10','Male','C001'),
('A002','D004','Nuwan','Silva','N002','R002','2003-08-15','Male','C002'),
('A003','D007','Sahan','Fernando','N003','R003','2005-02-20','Male','C003'),
('A004','D018','Dilan','Kumar','N004','R004','2004-11-05','Male','C004'),
('A005','D022','Amaya','Perera','N005','R005','2005-07-12','Female','C005'),
('A006','D024','Tharushi','Silva','N006','R006','2003-09-25','Female','C006');

INSERT INTO ATHLETE_CONTACT
(ATHLETE_ID,CONTACT_NO)
VALUES
('A001','0771111111'),
('A002','0772222222'),
('A003','0773333333'),
('A004','0774444444'),
('A005','0775555555'),
('A006','0776666666');

INSERT INTO EVENT
(SPORT_ID,VENUE_ID,EVENT_ID,EVENT_CODE,EVENT_NAME,EVENT_CATEGORY)
VALUES
('S001','V001','E001','100M01','100m Running','Individual'),
('S002','V001','E002','LJ01','Long Jump','Individual'),
('S003','V002','E003','SW01','100m Freestyle Swimming','Individual'),
('S004','V003','E004','CR01','Cricket Match','Team'),
('S005','V004','E005','FB01','Football Match','Team'),
('S006','V006','E006','VB01','Volleyball Match','Team');

INSERT INTO SPORT_MATCH
(MATCH_ID,MATCH_DATE,ROUND,EVENT_ID,VENUE_ID)
VALUES
('SM001','2026-01-10',1,'E001','V001'),
('SM002','2026-01-11',1,'E002','V001'),
('SM003','2026-01-12',1,'E003','V002'),
('SM004','2026-01-13',1,'E004','V003'),
('SM005','2026-01-14',2,'E005','V004'),
('SM006','2026-01-15',1,'E006','V006');


INSERT INTO PARTICIPATION
(PARTICIPANT_ID,EVENT_ID,ATHLETE_ID,RESULT,POSITION,REMARKS,MEDAL_ID)
VALUES
('P001','E001','A001','10.5 sec','1st','Excellent','M001'),
('P002','E002','A002','7.2 m','2nd','Good','M002'),
('P003','E003','A003','58 sec','3rd','Good','M003'),
('P004','E004','A004','Won','1st','Team Winner','M004'),
('P005','E005','A005','Won','1st','Final Winner','M005'),
('P006','E006','A006','Won','1st','Best Player','M006');

INSERT INTO INJURY_RECORD
(INJURY_ID,ATHLETE_ID,INJURY_DESCRIPTION,INJURY_DATE,RECOVERY_DATE,REMARKS)
VALUES
('I001','A001','Leg Injury','2026-02-01','2026-02-15','Recovered'),
('I002','A002','Shoulder Injury','2026-02-03','2026-02-20','Recovered'),
('I003','A003','Muscle Pain','2026-02-05','2026-02-10','Recovered'),
('I004','A004','Ankle Injury','2026-02-07','2026-02-25','Recovered'),
('I005','A005','Knee Injury','2026-02-09','2026-03-01','Recovered'),
('I006','A006','Back Pain','2026-02-11','2026-03-05','Recovered');

INSERT INTO DISTRICT_COMPETES
(District_Compete_ID,District_ID_1,District_ID_2,Event_ID,Match_Date,Venue,Winner_District_ID,Result,Remarks)
VALUES
('DC001','D001','D002','E004','2026-03-01','Colombo Stadium','D001','2-1','Final'),
('DC002','D004','D007','E005','2026-03-02','Kandy Stadium','D004','3-2','Semi Final'),
('DC003','D018','D019','E006','2026-03-03','Kurunegala Stadium','D018','25-20','League'),
('DC004','D022','D024','E004','2026-03-04','Badulla Ground','D022','1-0','Final'),
('DC005','D003','D006','E005','2026-03-05','Colombo Stadium','D006','2-1','Round 1'),
('DC006','D010','D015','E006','2026-03-06','Jaffna Ground','D010','30-25','League');


UPDATE Province
SET Province_Name='Western Province'
WHERE Province_ID='P001';
UPDATE Province
SET Province_Code='NCP'
WHERE Province_ID='P007';

UPDATE COACH
SET GENDER='Female'
WHERE COACH_ID='C001';
UPDATE COACH
SET LICENCE_NO='LIC_NEW002'
WHERE COACH_ID='C002';

DELETE FROM COACH
WHERE COACH_ID='C006';

UPDATE COACH_QUALIFICATION
SET QUALIFICATION='Advanced Athletics Coach'
WHERE COACH_ID='C001'
AND QUALIFICATION='Level 1 Athletics Coach';
UPDATE COACH_QUALIFICATION
SET QUALIFICATION='Advanced Cricket Coach'
WHERE COACH_ID='C002'
AND QUALIFICATION='Level 2 Cricket Coach';

DELETE FROM COACH_QUALIFICATION
WHERE COACH_ID='C005'
AND QUALIFICATION='National Coaching Certificate';

UPDATE ATHLETE
SET GENDER='Female'
WHERE ATHLETE_ID='A001';
UPDATE ATHLETE
SET REG_NO='NEW_R006'
WHERE ATHLETE_ID='A006';

DELETE FROM PARTICIPATION
WHERE ATHLETE_ID='A006';
DELETE FROM ATHLETE
WHERE ATHLETE_ID='A006';

UPDATE ATHLETE_CONTACT
SET CONTACT_NO='0711111111'
WHERE ATHLETE_ID='A001';
UPDATE ATHLETE_CONTACT
SET CONTACT_NO='0722222222'
WHERE ATHLETE_ID='A002';

DELETE FROM ATHLETE_CONTACT
WHERE ATHLETE_ID='A005'
AND CONTACT_NO='0775555555';

UPDATE SPORT
SET SPORT_NAME='100m Sprint Running'
WHERE SPORT_ID='S001';
UPDATE SPORT
SET SPORT_NAME='Football Tournament'
WHERE SPORT_ID='S005';

INSERT INTO SPORT
(SPORT_ID,SPORT_NAME)
VALUES
('S007','Basketball');
DELETE FROM SPORT
WHERE SPORT_ID='S007';

UPDATE VENUE
SET CAPACITY=30000
WHERE VENUE_ID='V001';
UPDATE VENUE
SET CITY='Kandy City'
WHERE VENUE_ID='V002';

INSERT INTO VENUE
(VENUE_ID,VENUE_NAME,CAPACITY,STREET,CITY,POSTAL_CODE)
VALUES
('V007','Temporary Ground',5000,'Main Road','Jaffna','40000');
DELETE FROM VENUE
WHERE VENUE_ID='V007';

UPDATE MEDAL
SET DESCRIPTION='Gold Winner Medal'
WHERE MEDAL_ID='M001';
UPDATE MEDAL
SET DESCRIPTION='Silver Winner Medal'
WHERE MEDAL_ID='M002';

INSERT INTO MEDAL
(MEDAL_ID,DESCRIPTION,MEDAL_TYPE)
VALUES
('M007','Temporary Medal','Gold');
DELETE FROM MEDAL
WHERE MEDAL_ID='M007';

UPDATE EVENT
SET EVENT_NAME='100m Sprint Final'
WHERE EVENT_ID='E001';
UPDATE EVENT
SET EVENT_CATEGORY='Relay'
WHERE EVENT_ID='E002';

DELETE FROM DISTRICT_COMPETES
WHERE Event_ID='E006';
DELETE FROM EVENT
WHERE EVENT_ID='E006';

UPDATE SPORT_MATCH
SET ROUND=2
WHERE MATCH_ID='SM001';
UPDATE SPORT_MATCH
SET MATCH_DATE='2026-02-15'
WHERE MATCH_ID='SM002';

DELETE FROM SPORT_MATCH
WHERE MATCH_ID='SM006';

UPDATE PARTICIPATION
SET REMARKS='Updated Performance'
WHERE ATHLETE_ID='A001'
AND EVENT_ID='E001'
AND PARTICIPANT_ID='P001';

DELETE FROM PARTICIPATION
WHERE ATHLETE_ID='A001'
AND EVENT_ID='E001'
AND PARTICIPANT_ID='P001';

UPDATE INJURY_RECORD
SET REMARKS='Under Treatment'
WHERE ATHLETE_ID='A001'
AND INJURY_ID='I001';

DELETE FROM INJURY_RECORD
WHERE ATHLETE_ID='A001'
AND INJURY_ID='I001';

UPDATE DISTRICT_COMPETES
SET RESULT='3-1'
WHERE District_Compete_ID='DC001';
UPDATE DISTRICT_COMPETES
SET Remarks='Updated Final'
WHERE District_Compete_ID='DC002';

DELETE FROM DISTRICT_COMPETES
WHERE District_Compete_ID='DC006';

-- Transactions
-- simple queries
SELECT *
FROM ATHLETE;

SELECT FULL_NAME, GENDER
FROM ATHLETE;

SELECT A.FULL_NAME, C.COACH_NAME
FROM ATHLETE A, COACH C;

CREATE VIEW Athlete_View AS
SELECT ATHLETE_ID, FULL_NAME, GENDER, DISTRICT_ID
FROM ATHLETE;

SELECT 
A.FULL_NAME AS Athlete_Name,
A.GENDER AS Athlete_Gender
FROM ATHLETE A;

SELECT 
AVG(CAPACITY) AS Average_Venue_Capacity
FROM VENUE;

SELECT 
FULL_NAME,
GENDER
FROM ATHLETE
WHERE FULL_NAME LIKE 'K%';

-- complex queries
-- 1
SELECT 
A.FULL_NAME AS PERSON_NAME
FROM ATHLETE A
UNION
SELECT 
C.COACH_NAME AS PERSON_NAME
FROM COACH C;

-- 2
SELECT ATHLETE_ID
FROM PARTICIPATION
INTERSECT
SELECT ATHLETE_ID
FROM INJURY_RECORD;

-- 3
SELECT 
A.ATHLETE_ID AS ID,
A.FULL_NAME AS ATHLETE_NAME
FROM ATHLETE A
WHERE A.ATHLETE_ID NOT IN
(
    SELECT 
    P.ATHLETE_ID
    FROM PARTICIPATION P
);

-- 4
SELECT 
A.ATHLETE_ID AS ID,
A.FULL_NAME AS ATHLETE_NAME

FROM ATHLETE A
WHERE NOT EXISTS
(
    SELECT E.EVENT_ID
    FROM EVENT E
    WHERE NOT EXISTS
    (
        SELECT P.EVENT_ID
        FROM PARTICIPATION P
        
        WHERE P.ATHLETE_ID=A.ATHLETE_ID
        AND P.EVENT_ID=E.EVENT_ID
    )
);

-- 5
CREATE VIEW Athlete_Participation_View AS
SELECT
A.ATHLETE_ID,
A.FULL_NAME,
P.EVENT_ID,
P.RESULT,
P.MEDAL_ID

FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID=P.ATHLETE_ID;

-- 5 query
SELECT
AP.FULL_NAME AS ATHLETE,
E.EVENT_NAME AS EVENT,
AP.RESULT AS RESULT

FROM Athlete_Participation_View AP
INNER JOIN EVENT E
ON AP.EVENT_ID=E.EVENT_ID;

-- 6
CREATE VIEW Sport_Event_View AS
SELECT
SPORT_ID,
EVENT_NAME
FROM EVENT;

-- 6 query
SELECT
S.SPORT_NAME AS SPORT,
SE.EVENT_NAME AS EVENT
FROM SPORT S
NATURAL JOIN Sport_Event_View SE;

-- 7
CREATE VIEW Athlete_Event_Left_View AS
SELECT
A.ATHLETE_ID,
A.FULL_NAME,
P.EVENT_ID
FROM ATHLETE A
LEFT JOIN PARTICIPATION P
ON A.ATHLETE_ID=P.ATHLETE_ID;

-- 7 query
SELECT
L.FULL_NAME AS ATHLETE,
L.EVENT_ID AS EVENT
FROM Athlete_Event_Left_View L;

-- 8
CREATE VIEW Event_Participation_Right_View AS
SELECT
E.EVENT_ID,
E.EVENT_NAME,
P.ATHLETE_ID
FROM PARTICIPATION P
RIGHT JOIN EVENT E
ON P.EVENT_ID=E.EVENT_ID;
 
-- 8 query
SELECT
R.EVENT_NAME AS EVENT,
R.ATHLETE_ID AS ATHLETE

FROM Event_Participation_Right_View R;

-- 9
CREATE VIEW Full_Event_Participation_View AS
SELECT
E.EVENT_NAME,
P.ATHLETE_ID
FROM EVENT E
LEFT JOIN PARTICIPATION P
ON E.EVENT_ID=P.EVENT_ID
UNION
SELECT
E.EVENT_NAME,
P.ATHLETE_ID
FROM EVENT E
RIGHT JOIN PARTICIPATION P
ON E.EVENT_ID=P.EVENT_ID;

-- 9 query
SELECT *
FROM Full_Event_Participation_View;

-- 10 quey
SELECT
A.ATHLETE_ID AS ID,
A.FULL_NAME AS NAME,
'ATHLETE' AS TYPE
FROM ATHLETE A
UNION
SELECT
C.COACH_ID AS ID,
C.COACH_NAME AS NAME,
'COACH' AS TYPE
FROM COACH C;

-- 11
SELECT
A.FULL_NAME AS ATHLETE
FROM ATHLETE A
WHERE
(
SELECT COUNT(*)
FROM PARTICIPATION P
WHERE P.ATHLETE_ID=A.ATHLETE_ID
) >
(
SELECT AVG(TOTAL)
FROM
(
SELECT COUNT(*) AS TOTAL
FROM PARTICIPATION
GROUP BY ATHLETE_ID
) X
);

-- 12
SELECT
A.FULL_NAME AS ATHLETE,
E.EVENT_NAME AS EVENT
FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID=P.ATHLETE_ID
JOIN EVENT E
ON P.EVENT_ID=E.EVENT_ID
WHERE P.MEDAL_ID IN
(
SELECT MEDAL_ID
FROM MEDAL
);

-- 13
SELECT
A.FULL_NAME AS ATHLETE,
E.EVENT_NAME AS EVENT
FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID=P.ATHLETE_ID
JOIN EVENT E
ON P.EVENT_ID=E.EVENT_ID
WHERE E.VENUE_ID IN
(
SELECT V.VENUE_ID
FROM VENUE V
WHERE V.CITY='Colombo'
);

-- TUNING!!!

-- QUERY 1 : INNER JOIN
-- Original Query

SELECT A.FULL_NAME,
       E.EVENT_NAME,
       P.RESULT,
       M.MEDAL_TYPE
FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID = P.ATHLETE_ID
JOIN EVENT E
ON P.EVENT_ID = E.EVENT_ID
JOIN MEDAL M
ON P.MEDAL_ID = M.MEDAL_ID;

-- EXPLAIN (Original)
EXPLAIN
SELECT A.FULL_NAME,
       E.EVENT_NAME,
       P.RESULT,
       M.MEDAL_TYPE
FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID = P.ATHLETE_ID
JOIN EVENT E
ON P.EVENT_ID = E.EVENT_ID
JOIN MEDAL M
ON P.MEDAL_ID = M.MEDAL_ID;

-- TUNING
CREATE INDEX IDX_PARTICIPATION_MEDAL
ON PARTICIPATION(MEDAL_ID);

-- Tuned Query
SELECT A.FULL_NAME,
       E.EVENT_NAME,
       P.RESULT,
       M.MEDAL_TYPE
FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID = P.ATHLETE_ID
JOIN EVENT E
ON P.EVENT_ID = E.EVENT_ID
JOIN MEDAL M
ON P.MEDAL_ID = M.MEDAL_ID;

-- EXPLAIN (Tuned)
EXPLAIN
SELECT A.FULL_NAME,
       E.EVENT_NAME,
       P.RESULT,
       M.MEDAL_TYPE
FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID = P.ATHLETE_ID
JOIN EVENT E
ON P.EVENT_ID = E.EVENT_ID
JOIN MEDAL M
ON P.MEDAL_ID = M.MEDAL_ID;

-- QUERY 2 : NATURAL JOIN
-- Original Query
SELECT A.ATHLETE_ID,
       A.FULL_NAME,
       C.CONTACT_NO
FROM ATHLETE A
NATURAL JOIN ATHLETE_CONTACT C;

-- EXPLAIN (Original)
EXPLAIN
SELECT A.ATHLETE_ID,
       A.FULL_NAME,
       C.CONTACT_NO
FROM ATHLETE A
NATURAL JOIN ATHLETE_CONTACT C;
-- TUNING
-- No additional index required.
-- ATHLETE_CONTACT.ATHLETE_ID is already indexed as part of the PRIMARY KEY.
-- Tuned Query
SELECT A.ATHLETE_ID,
       A.FULL_NAME,
       C.CONTACT_NO
FROM ATHLETE A
NATURAL JOIN ATHLETE_CONTACT C;

-- EXPLAIN (Tuned)
EXPLAIN
SELECT A.ATHLETE_ID,
       A.FULL_NAME,
       C.CONTACT_NO
FROM ATHLETE A
NATURAL JOIN ATHLETE_CONTACT C;

-- QUERY 3 : LEFT OUTER JOIN
-- Original Query
SELECT C.COACH_NAME,
       A.FULL_NAME
FROM COACH C
LEFT JOIN ATHLETE A
ON C.COACH_ID = A.COACH_ID;

-- EXPLAIN (Original)
EXPLAIN
SELECT C.COACH_NAME,
       A.FULL_NAME
FROM COACH C
LEFT JOIN ATHLETE A
ON C.COACH_ID = A.COACH_ID;

-- TUNING
CREATE INDEX IDX_ATHLETE_COACH
ON ATHLETE(COACH_ID);

-- Tuned Query
SELECT C.COACH_NAME,
       A.FULL_NAME
FROM COACH C
LEFT JOIN ATHLETE A
ON C.COACH_ID = A.COACH_ID;

-- EXPLAIN (Tuned)
EXPLAIN
SELECT C.COACH_NAME,
       A.FULL_NAME
FROM COACH C
LEFT JOIN ATHLETE A
ON C.COACH_ID = A.COACH_ID;

-- QUERY 4 : RIGHT OUTER JOIN
-- Original Query
SELECT D.DISTRICT_NAME,
       A.FULL_NAME
FROM ATHLETE A
RIGHT JOIN DISTRICT D
ON A.DISTRICT_ID = D.DISTRICT_ID;

-- EXPLAIN (Original)
EXPLAIN
SELECT D.DISTRICT_NAME,
       A.FULL_NAME
FROM ATHLETE A
RIGHT JOIN DISTRICT D
ON A.DISTRICT_ID = D.DISTRICT_ID;

-- TUNING
CREATE INDEX IDX_ATHLETE_DISTRICT
ON ATHLETE(DISTRICT_ID);

-- Tuned Query
SELECT D.DISTRICT_NAME,
       A.FULL_NAME
FROM ATHLETE A
RIGHT JOIN DISTRICT D
ON A.DISTRICT_ID = D.DISTRICT_ID;

-- EXPLAIN (Tuned)
EXPLAIN
SELECT D.DISTRICT_NAME,
       A.FULL_NAME
FROM ATHLETE A
RIGHT JOIN DISTRICT D
ON A.DISTRICT_ID = D.DISTRICT_ID;

-- QUERY 5 : FULL OUTER JOIN (Simulated using UNION)
-- Original Query
SELECT A.FULL_NAME,
       I.INJURY_DESCRIPTION
FROM ATHLETE A
LEFT JOIN INJURY_RECORD I
ON A.ATHLETE_ID = I.ATHLETE_ID

UNION

SELECT A.FULL_NAME,
       I.INJURY_DESCRIPTION
FROM ATHLETE A
RIGHT JOIN INJURY_RECORD I
ON A.ATHLETE_ID = I.ATHLETE_ID;

-- EXPLAIN (Original)

EXPLAIN
SELECT A.FULL_NAME,
       I.INJURY_DESCRIPTION
FROM ATHLETE A
LEFT JOIN INJURY_RECORD I
ON A.ATHLETE_ID = I.ATHLETE_ID

UNION

SELECT A.FULL_NAME,
       I.INJURY_DESCRIPTION
FROM ATHLETE A
RIGHT JOIN INJURY_RECORD I
ON A.ATHLETE_ID = I.ATHLETE_ID;

-- TUNING
-- No additional index required.
-- INJURY_RECORD.ATHLETE_ID is already indexed as part of the PRIMARY KEY.
-- Tuned Query
SELECT A.FULL_NAME,
       I.INJURY_DESCRIPTION
FROM ATHLETE A
LEFT JOIN INJURY_RECORD I
ON A.ATHLETE_ID = I.ATHLETE_ID

UNION

SELECT A.FULL_NAME,
       I.INJURY_DESCRIPTION
FROM ATHLETE A
RIGHT JOIN INJURY_RECORD I
ON A.ATHLETE_ID = I.ATHLETE_ID;

-- EXPLAIN (Tuned)
EXPLAIN
SELECT A.FULL_NAME,
       I.INJURY_DESCRIPTION
FROM ATHLETE A
LEFT JOIN INJURY_RECORD I
ON A.ATHLETE_ID = I.ATHLETE_ID
UNION
SELECT A.FULL_NAME,
       I.INJURY_DESCRIPTION
FROM ATHLETE A
RIGHT JOIN INJURY_RECORD I
ON A.ATHLETE_ID = I.ATHLETE_ID;


-- QUERY 6 : SEARCH ATHLETE BY GENDER
-- ORIGINAL QUERY
SELECT
A.ATHLETE_ID,
A.FULL_NAME,
A.GENDER,
A.DISTRICT_ID
FROM ATHLETE A
WHERE A.GENDER='Female';

-- EXPLAIN ORIGINAL
EXPLAIN
SELECT
A.ATHLETE_ID,
A.FULL_NAME,
A.GENDER,
A.DISTRICT_ID

FROM ATHLETE A

WHERE A.GENDER='Female';

-- TUNING
CREATE INDEX IDX_ATHLETE_GENDER
ON ATHLETE(GENDER);

-- TUNED QUERY
SELECT
A.ATHLETE_ID,
A.FULL_NAME,
A.GENDER,
A.DISTRICT_ID

FROM ATHLETE A

WHERE A.GENDER='Female';

-- EXPLAIN TUNED
EXPLAIN
SELECT
A.ATHLETE_ID,
A.FULL_NAME,
A.GENDER,
A.DISTRICT_ID

FROM ATHLETE A

WHERE A.GENDER='Female';

-- QUERY 7 : EVENT AND SPORT JOIN
-- ORIGINAL QUERY
SELECT
S.SPORT_NAME,
E.EVENT_NAME,
E.EVENT_CATEGORY

FROM SPORT S

JOIN EVENT E

ON S.SPORT_ID=E.SPORT_ID;

-- EXPLAIN ORIGINAL
EXPLAIN
SELECT
S.SPORT_NAME,
E.EVENT_NAME,
E.EVENT_CATEGORY

FROM SPORT S

JOIN EVENT E

ON S.SPORT_ID=E.SPORT_ID;

-- TUNING
CREATE INDEX IDX_EVENT_SPORT
ON EVENT(SPORT_ID);

-- TUNED QUERY
SELECT
S.SPORT_NAME,
E.EVENT_NAME,
E.EVENT_CATEGORY

FROM SPORT S

JOIN EVENT E

ON S.SPORT_ID=E.SPORT_ID;

-- EXPLAIN TUNED
EXPLAIN
SELECT
S.SPORT_NAME,
E.EVENT_NAME,
E.EVENT_CATEGORY

FROM SPORT S
JOIN EVENT E
ON S.SPORT_ID=E.SPORT_ID;

-- QUERY 8 : FIND MEDAL WINNERS
-- ORIGINAL QUERY
SELECT
A.FULL_NAME,
M.MEDAL_TYPE
FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID=P.ATHLETE_ID
JOIN MEDAL M
ON P.MEDAL_ID=M.MEDAL_ID
WHERE M.MEDAL_TYPE='Gold';

-- EXPLAIN ORIGINAL
EXPLAIN
SELECT
A.FULL_NAME,
M.MEDAL_TYPE
FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID=P.ATHLETE_ID
JOIN MEDAL M
ON P.MEDAL_ID=M.MEDAL_ID
WHERE M.MEDAL_TYPE='Gold';

-- TUNING
CREATE INDEX IDX_MEDAL_TYPE
ON MEDAL(MEDAL_TYPE);

-- TUNED QUERY
SELECT
A.FULL_NAME,
M.MEDAL_TYPE

FROM ATHLETE A

JOIN PARTICIPATION P

ON A.ATHLETE_ID=P.ATHLETE_ID

JOIN MEDAL M

ON P.MEDAL_ID=M.MEDAL_ID

WHERE M.MEDAL_TYPE='Gold';

-- EXPLAIN TUNED
EXPLAIN
SELECT
A.FULL_NAME,
M.MEDAL_TYPE
FROM ATHLETE A
JOIN PARTICIPATION P
ON A.ATHLETE_ID=P.ATHLETE_ID
JOIN MEDAL M
ON P.MEDAL_ID=M.MEDAL_ID
WHERE M.MEDAL_TYPE='Gold';

-- QUERY 9 : ATHLETE INJURY DETAILS
-- ORIGINAL QUERY
SELECT
A.FULL_NAME,
I.INJURY_DESCRIPTION,
I.INJURY_DATE
FROM ATHLETE A
JOIN INJURY_RECORD I
ON A.ATHLETE_ID=I.ATHLETE_ID;

-- EXPLAIN ORIGINAL
EXPLAIN
SELECT
A.FULL_NAME,
I.INJURY_DESCRIPTION,
I.INJURY_DATE
FROM ATHLETE A
JOIN INJURY_RECORD I
ON A.ATHLETE_ID=I.ATHLETE_ID;

-- TUNING
-- Already indexed
-- INJURY_RECORD.ATHLETE_ID is included in PRIMARY KEY
-- PRIMARY KEY(ATHLETE_ID,INJURY_ID)
SHOW INDEX FROM INJURY_RECORD;

-- TUNED QUERY
SELECT
A.FULL_NAME,
I.INJURY_DESCRIPTION,
I.INJURY_DATE
FROM ATHLETE A
JOIN INJURY_RECORD I
ON A.ATHLETE_ID=I.ATHLETE_ID;
-- EXPLAIN TUNED
EXPLAIN
SELECT
A.FULL_NAME,
I.INJURY_DESCRIPTION,
I.INJURY_DATE
FROM ATHLETE A
JOIN INJURY_RECORD I
ON A.ATHLETE_ID=I.ATHLETE_ID;

-- QUERY 10 : DISTRICT COMPETITION DETAILS
-- ORIGINAL QUERY
SELECT
D.District_Name,
DC.Result,
DC.Remarks
FROM DISTRICT D
JOIN DISTRICT_COMPETES DC
ON D.District_ID=DC.District_ID_1;

-- EXPLAIN ORIGINAL
EXPLAIN
SELECT
D.District_Name,
DC.Result,
DC.Remarks
FROM DISTRICT D
JOIN DISTRICT_COMPETES DC
ON D.District_ID=DC.District_ID_1;

-- TUNING
CREATE INDEX IDX_DC_DISTRICT1
ON DISTRICT_COMPETES(District_ID_1);

-- TUNED QUERY
SELECT
D.District_Name,
DC.Result,
DC.Remarks
FROM DISTRICT D
JOIN DISTRICT_COMPETES DC
ON D.District_ID=DC.District_ID_1;

-- EXPLAIN TUNED
EXPLAIN
SELECT
D.District_Name,
DC.Result,
DC.Remarks
FROM DISTRICT D
JOIN DISTRICT_COMPETES DC
ON D.District_ID=DC.District_ID_1;


